name: Upload Lambda to S3

on:
  pull_request:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Package Lambda Function
        run: |
          zip -r lambda_function.zip .

      
      - name: Configure AWS Credentials for Demo
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_DEMO}}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_DEMO}}
          aws-region: us-west-2

      - name: Create S3 Bucket in Demo (if not exists)
        run: |
          aws s3 mb s3://webapp-manav || true

      - name: Upload to S3 Demo
        run: |
          aws s3 cp lambda_function.zip s3://webapp-manav/lambda_function.zip

      
      # - name: Configure AWS Credentials for Dev
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.ACCESS_KEY}}
      #     aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
      #     aws-region: us-west-2 

      # - name: Create S3 Bucket in Dev (if not exists)
      #   run: |
      #     aws s3 mb s3://webapp-manav || true

      # - name: Upload to S3 Dev
      #   run: |
      #     aws s3 cp lambda_function.zip s3://webapp-manav/lambda_function.zip
