name: Upload Lambda to S3

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Package Lambda Function
        run: |
          zip -r lambda_function.zip .

      - name: Install Dependencies
        run: echo $ACCESS_KEY $SECRET_ACCESS_KEY
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY}}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY}}

      - name: Configure AWS Credentials for iamadmin-webapp
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
          aws-region: us-west-2

      - name: Create S3 Bucket in iamadmin-webapp (if not exists)
        run: |
          aws s3 mb s3://webapp-manav || true

      - name: Upload to S3 
        run: |
          aws s3 cp lambda_function.zip s3://webapp-manav/lambda_function.zip
